### PR TITLE
Added support for raw TAP results as third argument to callback

### PR DESCRIPTION
**Pull request by andrewdeandrade**
This pull requests passes the raw TAP results returned by this PR here https://github.com/conradz/wd-tap/pull/3 along to the user.

### CODE REVIEW

**Comment by MoOx** [comment]
+1 for this.

**Comment by conradz** [comment]
Sorry for leaving this hanging. The one thing I don't like about this is that there is more than one result passed to the callback, which is a little unusual. I would like it to be an added property to the TAP results object, probably named `.raw`.

**Comment by MoOx** [comment]
Are you ok with `(err, results) => results._raw` ? I can handle the PR if @malandrew is on something else :)

**Comment by conradz** [comment]
I would propose `(err, results) => results.raw`, at least as long as the `tap-parser` results object does not contain the same property name already.

**Pull request closed without merging**
